package com.docsbot.ops.migration;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.DriverManager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("postgres")
class LegacySqliteImportIntegrationTest {

    @Autowired
    private LegacySqliteImportService importService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private Path sourceDatabase;

    @BeforeEach
    void prepare() throws Exception {
        jdbcTemplate.execute("""
                create table if not exists legacy_import_runs (
                    id bigint generated by default as identity primary key,
                    source_path varchar(4000) not null,
                    source_checksum varchar(64) not null,
                    status varchar(32) not null,
                    documents_inserted integer not null default 0,
                    tenders_inserted integer not null default 0,
                    bindings_inserted integer not null default 0,
                    setups_inserted integer not null default 0,
                    organizations_inserted integer not null default 0,
                    skipped_rows integer not null default 0,
                    error_message varchar(4000),
                    started_at timestamp with time zone not null,
                    completed_at timestamp with time zone
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists telegram_chat_bindings (
                    id bigint generated by default as identity primary key,
                    chat_id varchar(64) not null unique,
                    chat_title varchar(255),
                    tender_id varchar(128) not null,
                    created_at timestamp with time zone not null,
                    updated_at timestamp with time zone not null
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists telegram_chat_setups (
                    id bigint generated by default as identity primary key,
                    chat_id varchar(64) not null unique,
                    chat_title varchar(255),
                    internal_unit varchar(64),
                    updated_at timestamp with time zone not null
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists tender_organizations (
                    id bigint generated by default as identity primary key,
                    code varchar(64) not null unique,
                    name varchar(255) not null unique,
                    active integer not null,
                    created_at timestamp with time zone not null
                )
                """);
        jdbcTemplate.update("delete from erp_task_documents");
        jdbcTemplate.update("delete from documents");
        jdbcTemplate.update("delete from telegram_chat_bindings");
        jdbcTemplate.update("delete from telegram_chat_setups");
        jdbcTemplate.update("delete from tenders");
        jdbcTemplate.update("delete from tender_organizations");
        jdbcTemplate.update("delete from legacy_import_runs");

        Path root = Path.of("target", "test-data").toAbsolutePath().normalize();
        Files.createDirectories(root.resolve("originals"));
        Path storedFile = root.resolve("originals").resolve("sample.txt");
        Files.writeString(storedFile, "legacy file");

        sourceDatabase = Path.of("target", "legacy-import-test.sqlite3")
                .toAbsolutePath()
                .normalize();
        Files.deleteIfExists(sourceDatabase);
        createLegacyDatabase(sourceDatabase, storedFile);
    }

    @Test
    void importsLegacyTenderDataAndIsIdempotent() {
        LegacySqliteImportService.ImportReport first =
                importService.importDatabase(sourceDatabase);

        assertThat(first.documentsInserted()).isEqualTo(1);
        assertThat(first.tendersInserted()).isEqualTo(1);
        assertThat(first.bindingsInserted()).isEqualTo(1);
        assertThat(first.setupsInserted()).isEqualTo(1);
        assertThat(first.organizationsInserted()).isEqualTo(1);
        assertThat(first.skippedRows()).isZero();
        assertThat(jdbcTemplate.queryForObject(
                "select file_path from documents where message_id='legacy-message-1'",
                String.class)).isEqualTo("originals/sample.txt");

        LegacySqliteImportService.ImportReport second =
                importService.importDatabase(sourceDatabase);

        assertThat(second.documentsInserted()).isZero();
        assertThat(second.tendersInserted()).isZero();
        assertThat(second.bindingsInserted()).isZero();
        assertThat(second.setupsInserted()).isZero();
        assertThat(second.organizationsInserted()).isZero();
        assertThat(second.skippedRows()).isEqualTo(5);
        assertThat(jdbcTemplate.queryForObject(
                "select count(*) from legacy_import_runs where status='completed'",
                Integer.class)).isEqualTo(2);
    }

    @Test
    void upgradesOlderLegacySchemaBeforeImporting() throws Exception {
        Files.deleteIfExists(sourceDatabase);
        createOlderLegacyDatabase(sourceDatabase);

        LegacySqliteImportService.ImportReport report =
                importService.importDatabase(sourceDatabase);

        assertThat(report.documentsInserted()).isEqualTo(1);
        assertThat(report.tendersInserted()).isEqualTo(1);
        assertThat(report.bindingsInserted()).isZero();
        assertThat(report.setupsInserted()).isZero();
        assertThat(report.organizationsInserted()).isZero();
        assertThat(report.skippedRows()).isZero();
        assertThat(jdbcTemplate.queryForObject(
                "select source from documents where message_id='older-message-1'",
                String.class)).isEqualTo("telegram");
        assertThat(jdbcTemplate.queryForObject(
                "select document_type from documents where message_id='older-message-1'",
                String.class)).isEqualTo("unknown");
        assertThat(jdbcTemplate.queryForObject(
                "select status from tenders where tender_id='OLDER-2026-001'",
                String.class)).isEqualTo("active");
    }

    private void createLegacyDatabase(Path database, Path storedFile) throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:sqlite:" + database);
             var statement = connection.createStatement()) {
            statement.execute("""
                    create table documents (
                        id integer primary key,
                        message_id text not null,
                        sender_hash text not null,
                        source text not null,
                        timestamp text not null,
                        media_id text not null,
                        mime_type text,
                        original_filename text,
                        stored_filename text,
                        caption text,
                        checksum text,
                        file_path text,
                        file_size integer,
                        internal_unit text,
                        organization text,
                        year integer,
                        tender_id text not null,
                        document_type text not null,
                        status text not null,
                        error_message text,
                        created_at text not null
                    )
                    """);
            statement.execute("""
                    create table tenders (
                        id integer primary key,
                        tender_id text not null,
                        organization text not null,
                        year integer not null,
                        sequence integer not null,
                        internal_unit text,
                        title text,
                        status text not null,
                        created_at text not null
                    )
                    """);
            statement.execute("""
                    create table telegram_chat_bindings (
                        id integer primary key,
                        chat_id text not null,
                        chat_title text,
                        tender_id text not null,
                        created_at text not null,
                        updated_at text not null
                    )
                    """);
            statement.execute("""
                    create table telegram_chat_setups (
                        id integer primary key,
                        chat_id text not null,
                        chat_title text,
                        internal_unit text,
                        updated_at text not null
                    )
                    """);
            statement.execute("""
                    create table tender_organizations (
                        id integer primary key,
                        code text not null,
                        name text not null,
                        active integer not null,
                        created_at text not null
                    )
                    """);
        }

        try (var connection = DriverManager.getConnection("jdbc:sqlite:" + database)) {
            try (var statement = connection.prepareStatement("""
                    insert into tender_organizations
                        (id, code, name, active, created_at)
                    values (1, 'BEDAS', 'BEDAS', 1, '2026-06-09 10:00:00')
                    """)) {
                statement.executeUpdate();
            }
            try (var statement = connection.prepareStatement("""
                    insert into tenders
                        (id, tender_id, organization, year, sequence, internal_unit,
                         title, status, created_at)
                    values (1, 'BEDAS-2026-001', 'BEDAS', 2026, 1, 'MOBIT',
                            'Legacy tender', 'active', '2026-06-09 10:00:00.123456')
                    """)) {
                statement.executeUpdate();
            }
            try (var statement = connection.prepareStatement("""
                    insert into documents (
                        id, message_id, sender_hash, source, timestamp, media_id,
                        mime_type, original_filename, stored_filename, checksum,
                        file_path, file_size, internal_unit, organization, year,
                        tender_id, document_type, status, created_at
                    ) values (
                        1, 'legacy-message-1', 'hashed', 'telegram',
                        '2026-06-09 10:01:00', 'media-1', 'text/plain',
                        'sample.txt', 'sample.txt', 'checksum-1', ?, 11, 'MOBIT',
                        'BEDAS', 2026, 'BEDAS-2026-001', 'technical_spec',
                        'stored', '2026-06-09 10:01:01'
                    )
                    """)) {
                statement.setString(1, storedFile.toString());
                statement.executeUpdate();
            }
            try (var statement = connection.prepareStatement("""
                    insert into telegram_chat_setups
                        (id, chat_id, chat_title, internal_unit, updated_at)
                    values (1, '-1001', 'Legacy group', 'MOBIT', '2026-06-09 10:00:00')
                    """)) {
                statement.executeUpdate();
            }
            try (var statement = connection.prepareStatement("""
                    insert into telegram_chat_bindings
                        (id, chat_id, chat_title, tender_id, created_at, updated_at)
                    values (1, '-1001', 'Legacy group', 'BEDAS-2026-001',
                            '2026-06-09 10:00:00', '2026-06-09 10:00:00')
                    """)) {
                statement.executeUpdate();
            }
        }
    }

    private void createOlderLegacyDatabase(Path database) throws Exception {
        try (var connection = DriverManager.getConnection("jdbc:sqlite:" + database);
             var statement = connection.createStatement()) {
            statement.execute("""
                    create table documents (
                        id integer primary key,
                        message_id text not null,
                        sender_hash text not null,
                        timestamp text not null,
                        media_id text not null,
                        mime_type text,
                        original_filename text,
                        caption text,
                        tender_id text not null
                    )
                    """);
            statement.execute("""
                    create table tenders (
                        id integer primary key,
                        tender_id text not null,
                        organization text not null,
                        year integer not null,
                        sequence integer not null
                    )
                    """);
        }

        try (var connection = DriverManager.getConnection("jdbc:sqlite:" + database)) {
            try (var statement = connection.prepareStatement("""
                    insert into tenders
                        (id, tender_id, organization, year, sequence)
                    values (1, 'OLDER-2026-001', 'OLDER', 2026, 1)
                    """)) {
                statement.executeUpdate();
            }
            try (var statement = connection.prepareStatement("""
                    insert into documents (
                        id, message_id, sender_hash, timestamp, media_id,
                        mime_type, original_filename, caption, tender_id
                    ) values (
                        1, 'older-message-1', 'hashed', '2026-06-09 10:01:00',
                        'media-older-1', 'text/plain', 'older.txt',
                        'Older schema document', 'OLDER-2026-001'
                    )
                    """)) {
                statement.executeUpdate();
            }
        }
    }
}
